trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    jobs:
      - job: BuildFrontend
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "22.x"
          - script: npm ci
          - script: npm run build
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "dist"
              ArtifactName: "frontend-drop"

  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: DeployStaticWebApp
        environment: "prod-frontend"
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: frontend-drop
                - task: AzureStaticWebApp@0
                  inputs:
                    app_location: "$(Pipeline.Workspace)/frontend-drop"
                    skip_app_build: true
                    azure_static_web_apps_api_token: "$(AZURE_STATIC_WEB_APPS_API_TOKEN)"
